### ISSUE TITLE
Multiple small issues from meeting 12/01/2024. 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/fsspark#8]
- [x] Main priority is the creation of the CPTAC dataset #2 #3 using the phosphoproteomics and acetylome data. 
- [x] Review all the algorithms and see which one are loading everything in memory and which ones are parallelizing all the compute.
- [x] Review other libraries that provide FS methods in Spark and reuse some of the algorithms.  

Small issues: 

- [x] `response` in the file format must be changed to `label`
- [x] The example should contain letter such as A, B, C rather than binary notation. 
- [x] Make sure the example (small example) always refer to gene expression and not protein expression. It is a GEO dataset. 
- [x] Annotate for every algorithm if is provided by Spark or is implemented by us.

**Comment by enriquea** [comment]
> * Annotate for every algorithm if is provided by Spark or is implemented by us.

For this small issue, I would like to tag (label) every function with decorators. Do you know how to implement that?
